{% set name = "pyopengl-accelerate" %}
{% set version = "3.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 82751c83f0a6f732b8b5923990edc2441d38176a98756b1718e8d6c4379f5a71
  # patches:
  #   # - long_type.patch # patch required to fix: https://github.com/mcfletch/pyopengl/pull/155
  #   - 0001-change-long-to-int.patch
build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - cython >=3                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython >=3

  run:
    - python
    - numpy
    - pyopengl =={{ version }}

test:
  requires:
    - pytest

  source_files:
    - tests

  imports:
    - OpenGL_accelerate
    - OpenGL_accelerate.numpy_formathandler
    - OpenGL_accelerate.arraydatatype
    - OpenGL_accelerate.buffers_formathandler
    - OpenGL_accelerate.wrapper
    - OpenGL_accelerate.vbo
    - OpenGL_accelerate.latebind
    - OpenGL_accelerate.errorchecker
    - OpenGL_accelerate.nones_formathandler
  commands:
    - pytest tests  # [not linux]

about:
  home: http://pyopengl.sourceforge.net
  license: LicenseRef-pyopengl
  license_file: license.txt
  summary: Acceleration code for PyOpenGL
  doc_url: http://pyopengl.sourceforge.net/documentation/index.html
  doc_source_url: https://sourceforge.net/projects/pyopengl/
  dev_url: https://github.com/mcfletch/pyopengl

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
